import type { Metadata } from 'next';
import { Fleur_De_Leah, Libre_Baskerville } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';

const fleurDeLeah = Fleur_De_Leah({
  variable: '--font-display',
  weight: '400',
  subsets: ['latin'],
});

const libreBaskerville = Libre_Baskerville({
  variable: '--font-libre-serif',
  weight: ['400', '700'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      className={cn(
        'h-full',
        'antialiased',
        fleurDeLeah.variable,
        libreBaskerville.variable,
        'font-sans'
      )}
    >
      <body className='min-h-full flex flex-col'>{children}</body>
    </html>
  );
}
