import type { Metadata } from 'next';
import { Fleur_De_Leah, Libre_Baskerville, Noto_Sans } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import { Providers } from '@/components/app/providers';
import { Sidebar } from '@/components/app/sidebar';
import { SidebarProvider } from '@/components/ui/sidebar';

const fleurDeLeah = Fleur_De_Leah({
  variable: '--font-display',
  weight: '400',
  subsets: ['latin'],
});

const notoSans = Noto_Sans({
  variable: '--font-noto-sans',
  weight: ['400', '500', '600'],
  subsets: ['latin'],
});

const libreBaskerville = Libre_Baskerville({
  variable: '--font-libre-serif',
  weight: ['400', '700'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      suppressHydrationWarning
      className={cn(
        'h-full',
        'antialiased',
        fleurDeLeah.variable,
        libreBaskerville.variable,
        notoSans.variable,
        'font-serif'
      )}
    >
      <body className='min-h-full flex flex-col'>
        <Providers>
          <SidebarProvider>
            <Sidebar />
            <main className='flex-1 min-h-[100vh] p-lg'>{children}</main>
          </SidebarProvider>
        </Providers>
      </body>
    </html>
  );
}
